[package]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.2.2"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-lang/crates.io"
description = "Backend of crates.io"
edition = "2021"
default-run = "server"

[workspace]

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
doctest = true

[[test]]
name = "all"
path = "src/tests/all.rs"

[dependencies]
anyhow = "=1.0.68"
aws-sigv4 = "=0.53.0"
axum = { version = "=0.6.4", features = ["headers", "macros", "matched-path"] }
axum-extra = { version = "=0.4.2", features = ["cookie-signed"] }
base64 = "=0.13.1"
cargo-registry-index = { path = "cargo-registry-index" }
cargo-registry-markdown = { path = "cargo-registry-markdown" }
cargo-registry-s3 = { path = "cargo-registry-s3" }
chrono = { version = "=0.4.23", features = ["serde"] }
clap = { version = "=4.1.4", features = ["derive", "env", "unicode", "wrap_help"] }
cookie = { version = "=0.17.0", features = ["secure"] }
dashmap = { version = "=5.4.0", features = ["raw-api"] }
derive_deref = "=1.1.1"
dialoguer = "=0.10.3"
diesel = { version = "=1.4.8", features = ["postgres", "serde_json", "chrono", "r2d2"] }
diesel_full_text_search = "=1.0.1"
diesel_migrations = { version = "=1.4.0", features = ["postgres"] }
dotenv = "=0.15.0"
flate2 = "=1.0.25"
futures-channel = { version = "=0.3.25", default-features = false }
futures-util = "=0.3.25"
hex = "=0.4.3"
http = "=0.2.8"
http-body = "=0.4.5"
hyper = { version = "=0.14.23", features = ["client", "http1"] }
indexmap = { version = "=1.9.2", features = ["serde-1"] }
indicatif = "=0.17.3"
ipnetwork = "=0.20.0"
tikv-jemallocator = { version = "=0.5.0", features = ['unprefixed_malloc_on_supported_platforms', 'profiling'] }
lettre = { version = "=0.10.1", default-features = false, features = ["file-transport", "smtp-transport", "native-tls", "hostname", "builder"] }
minijinja = "=0.30.1"
moka = { version = "=0.9.6", features = ["future"]  }
oauth2 = { version = "=4.3.0", default-features = false, features = ["reqwest"] }
once_cell = "=1.17.0"
parking_lot = "=0.12.1"
prometheus = { version = "=0.13.3", default-features = false }
rand = "=0.8.5"
reqwest = { version = "=0.11.14", features = ["blocking", "gzip", "json"] }
retry = "=2.0.0"
ring = "=0.16.20"
scheduled-thread-pool = "=0.2.6"
semver = { version = "=1.0.16", features = ["serde"] }
sentry = { version = "=0.29.1", features = ["tracing", "tower", "tower-http"] }
serde = { version = "=1.0.152", features = ["derive"] }
serde_json = "=1.0.91"
sha2 = "=0.10.6"
spdx = "=0.10.0"
tar = "=0.4.38"
tempfile = "=3.3.0"
thiserror = "=1.0.38"
threadpool = "=1.8.1"
tokio = { version = "=1.24.2", features = ["net", "signal", "io-std", "io-util", "rt-multi-thread", "macros"]}
toml = "=0.5.11"
tower = "=0.4.13"
tower-http = { version = "=0.3.5", features = ["fs"] }
tracing = "=0.1.37"
tracing-subscriber = { version = "=0.3.16", features = ["env-filter"] }
url = "=2.3.1"

[dev-dependencies]
cargo-registry-index = { path = "cargo-registry-index", features = ["testing"] }
claims = "=0.7.1"
hyper-tls = "=0.5.0"
insta = { version = "=1.26.0", features = ["redactions", "yaml"] }
tokio = "=1.24.2"
tower-service = "=0.3.2"

[build-dependencies]
diesel = { version = "=1.4.8", features = ["postgres"] }
diesel_migrations = { version = "=1.4.0", features = ["postgres"] }
dotenv = "=0.15.0"
